package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/IamAngusU/ByeClaude/internal/gitx"
)

func resolvedGitHookPath(repo *gitx.Repo, hookName string) (string, error) {
	if hookName != "commit-msg" && hookName != "pre-push" {
		return "", fmt.Errorf("unsupported hook: %q", hookName)
	}
	out, err := repo.Run("rev-parse", "--git-path", "hooks/"+hookName)
	if err != nil {
		return "", fmt.Errorf("resolve Git hook path: %w", err)
	}
	path := strings.TrimSpace(string(out))
	if path == "" {
		return "", fmt.Errorf("Git returned an empty hook path")
	}
	if !filepath.IsAbs(path) {
		path = filepath.Join(repo.Root, path)
	}
	return filepath.Clean(path), nil
}

type managedHook struct {
	Executable string
	RulesFile  string
}

// parseQuotedShellArg accepts exactly the single-quoted syntax generated by
// shellQuote. A header comment or a substring matching "hook-filter" alone
// never proves ownership of executable hook code.
func parseQuotedShellArg(s string) (value, remainder string, ok bool) {
	if !strings.HasPrefix(s, "'") {
		return "", "", false
	}
	s = s[1:]
	var b strings.Builder
	for {
		end := strings.IndexByte(s, '\'')
		if end < 0 {
			return "", "", false
		}
		b.WriteString(s[:end])
		s = s[end+1:]
		if strings.HasPrefix(s, "\\''") {
			b.WriteByte('\'')
			s = s[3:]
			continue
		}
		return b.String(), s, true
	}
}

func parseManagedHook(name string, source []byte) (managedHook, bool) {
	var result managedHook
	if name != "commit-msg" && name != "pre-push" {
		return result, false
	}
	lines := strings.Split(string(source), "\n")
	if len(lines) != 4 || lines[0] != "#!/bin/sh" ||
		lines[1] != "# Installed by ByeClaude." || lines[3] != "" {
		return result, false
	}
	line := lines[2]
	if !strings.HasPrefix(line, "exec ") {
		return result, false
	}
	executable, rest, ok := parseQuotedShellArg(strings.TrimPrefix(line, "exec "))
	if !ok {
		return result, false
	}
	executable = filepath.FromSlash(executable)
	if executable == "" || !filepath.IsAbs(executable) {
		return result, false
	}
	command, suffix := " hook-filter", ` "$1"`
	if name == "pre-push" {
		command, suffix = " pre-push-filter", ` "$@"`
	}
	if !strings.HasPrefix(rest, command) {
		return result, false
	}
	rest = strings.TrimPrefix(rest, command)
	var rulesFile string
	if strings.HasPrefix(rest, " --rules ") {
		rulesFile, rest, ok = parseQuotedShellArg(strings.TrimPrefix(rest, " --rules "))
		if !ok {
			return result, false
		}
		rulesFile = filepath.FromSlash(rulesFile)
		if !filepath.IsAbs(rulesFile) {
			return result, false
		}
	}
	if rest != suffix {
		return result, false
	}
	return managedHook{Executable: executable, RulesFile: rulesFile}, true
}

func ownedByeClaudeHook(name string, content []byte) bool {
	_, ok := parseManagedHook(name, content)
	return ok
}

func hookBinaryPath(name, script string) (string, bool) {
	managed, ok := parseManagedHook(name, []byte(script))
	return managed.Executable, ok
}

func ephemeralGoExecutable(path string) bool {
	normalized := filepath.ToSlash(path)
	base := strings.ToLower(filepath.Base(path))
	if strings.HasSuffix(base, ".test") || strings.HasSuffix(base, ".test.exe") {
		return false
	}
	return strings.Contains(normalized, "/go-build") && strings.Contains(normalized, "/exe/")
}

type inspectedHook struct {
	Name   string
	Path   string
	Status string
	RulesFile string
}

func inspectHook(repo *gitx.Repo, name string) (inspectedHook, error) {
	result := inspectedHook{Name: name, Status: "missing"}
	path, err := resolvedGitHookPath(repo, name)
	if err != nil {
		return result, err
	}
	result.Path = path
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return result, nil
	}
	if err != nil {
		return result, err
	}
	if !info.Mode().IsRegular() {
		result.Status = "conflict"
		return result, nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return result, err
	}
	managed, ok := parseManagedHook(name, data)
	if !ok {
		result.Status = "conflict"
		return result, nil
	}
	result.RulesFile = managed.RulesFile
	if _, err := os.Stat(managed.Executable); os.IsNotExist(err) {
		result.Status = "stale_binary"
		return result, nil
	} else if err != nil {
		return result, err
	}
	if managed.RulesFile != "" {
		if _, err := resolveMatcher(managed.RulesFile); err != nil {
			result.Status = "stale_rules"
			return result, nil
		}
	}
	if info.Mode()&0111 == 0 {
		result.Status = "not_executable"
		return result, nil
	}
	result.Status = "installed"
	return result, nil
}

func effectiveHooksPath(repo *gitx.Repo) (string, error) {
	out, found, err := repo.RunOptional("config", "--path", "--get", "core.hooksPath")
	if err != nil {
		return "", err
	}
	if found {
		return strings.TrimSpace(string(out)), nil
	}
	return "", nil
}

func resolveRulesFile(repo *gitx.Repo, input string) (string, error) {
	if strings.TrimSpace(input) == "" {
		return "", nil
	}
	path := input
	if !filepath.IsAbs(path) {
		path = filepath.Join(repo.Root, path)
	}
	path, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	if _, err := resolveMatcher(path); err != nil {
		return "", fmt.Errorf("invalid rules file %q: %w", path, err)
	}
	return path, nil
}
